androidx.paging.PagingData
kotlinx.collections.immutable.ImmutableList
kotlinx.collections.immutable.ImmutableMap
kotlinx.collections.immutable.ImmutableSet
kotlinx.collections.immutable.PersistentList
kotlinx.collections.immutable.PersistentMap
